### ISSUE TITLE
Failed to set up owlet connection - V2 Sock with version 2024.3.1

### ISSUE THREAD

**Issue by patrickbard** [ryanbdclark/owlet#15]
When I tried to use the integration (v 2024.3.1), it says it failed to set up:

![image](https://github.com/ryanbdclark/owlet/assets/3281217/6901c84d-37af-496d-ada7-a2b9f85e0f05)

Here is the log:
```python
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <MY_EMAIL>@gmail.com for owlet
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/owlet/__init__.py", line 75, in async_setup_entry
    socks = {
            ^
  File "/config/custom_components/owlet/__init__.py", line 76, in 
    device["device"]["dsn"]: Sock(owlet_api, device["device"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyowletapi/sock.py", line 84, in __init__
    self._manuf_model = data["manuf_model"]
                        ~~~~^^^^^^^^^^^^^^^
KeyError: 'manuf_model'
```

First I thought that was because I have a V2 Sock, but I saw that you added support in #8 (v  2023.11.2).

**Comment by patrickbard** [comment]
I updated to the new release and got a different error.

When initializing, either the old integration, or by creating a new one from scratch, it logs this:

```
2024-07-09 01:23:58.384 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform owlet.binary_sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
2024-07-09 01:23:58.388 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform owlet.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
```

Whenever I tried to reload the integration, it logs this:

```python
2024-07-09 01:26:48.639 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry patrickthiagobard+owlet@gmail.com for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 175, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-07-09 01:26:48.642 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry patrickthiagobard+owlet@gmail.com for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by patrickbard** [comment]
I updated to the new release and got a different error.

When initializing, either the old integration, or by creating a new one from scratch, it logs this:

```
2024-07-09 01:23:58.384 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform owlet.binary_sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
2024-07-09 01:23:58.388 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform owlet.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
```

Whenever I tried to reload the integration, it logs this:

```python
2024-07-09 01:26:48.639 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry <MY_EMAIL>@gmail.com for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 175, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-07-09 01:26:48.642 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry <MY_EMAIL>@gmail.com for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by ryanbdclark** [comment]
This happens when you are running an old version of home assistant. There was a change around 8 months ago that moved the DeviceInfo class. If you update your home assistant install to either the latest 2024.7.1 or even 2024.1 onwards should resolve this.

**Comment by patrickbard** [comment]
> This happens when you are running an old version of home assistant. There was a change around 8 months ago that moved the DeviceInfo class. If you update your home assistant install to either the latest 2024.7.1 or even 2024.1 onwards should resolve this.

I forgot to confirm here, but that indeed solved my issue and I was able to use it after updating.
